<?php
/**
 * Title: Counter Grid With Background
 * Slug: counter-grid-with-background
 * Categories: codemanas
 * Keywords: codemanas
 * Block Types: codemanas/cmblocks--counter
 */
if (!defined('ABSPATH')) {
	exit; // Exit if accessed directly
}
?>
<!-- wp:group {"align":"wide","style":{"spacing":{"padding":{"top":"0","bottom":"0","left":"0","right":"0"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignwide" style="padding-top:0;padding-right:0;padding-bottom:0;padding-left:0"><!-- wp:cover {"url":"<?php  echo esc_url( plugin_dir_url(__DIR__) .'assets/clocks.jpg'); ?>","id":761,"dimRatio":60,"align":"wide","style":{"spacing":{"padding":{"top":"var:preset|spacing|40","bottom":"var:preset|spacing|40","left":"var:preset|spacing|50","right":"var:preset|spacing|50"}}},"layout":{"type":"constrained"}} -->
	<div class="wp-block-cover alignwide" style="padding-top:var(--wp--preset--spacing--40);padding-right:var(--wp--preset--spacing--50);padding-bottom:var(--wp--preset--spacing--40);padding-left:var(--wp--preset--spacing--50)"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-60 has-background-dim"></span><img class="wp-block-cover__image-background wp-image-761" alt="" src="<?php  echo esc_url( plugin_dir_url(__DIR__) .'assets/clocks.jpg'); ?>" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:columns -->
			<div class="wp-block-columns"><!-- wp:column {"style":{"color":{"background":"#cccccc57"}}} -->
				<div class="wp-block-column has-background" style="background-color:#cccccc57"><!-- wp:cmblocks/counter {"title":"Satisfied Customers","endValue":"40","duration":"500","suffix":"k","titleColor":"#ffffff","counterColor":"#ffffff","suffixColor":"#ffffff","counterFontSize":"3.27rem","titleFontSize":"1.05rem","counterAlignment":"center","titleAlignment":"center","startFromScratch":true,"style":{"typography":{"textTransform":"none","fontStyle":"normal","fontWeight":"600"},"spacing":{"padding":{"top":"var:preset|spacing|40","bottom":"var:preset|spacing|40","left":"0","right":"0"}}}} -->
					<div class="wp-block-cmblocks-counter cmblocks-counter" style="padding-top:var(--wp--preset--spacing--40);padding-right:0;padding-bottom:var(--wp--preset--spacing--40);padding-left:0;font-style:normal;font-weight:600;text-transform:none;background:" role="timer" aria-live="polite" aria-label="<?php esc_html_e('Counter', 'cm-blocks'); ?>"><div class="cmblocks-counter__wrapper" style="background:" data-end-value="40" data-start-value="0" data-duration="500" data-separator=""><div class="cmblocks-counter__main" style="justify-content:center"><div class="cmblocks-counter__prefix" style="color:;padding-right:0;font-size:3.27rem"></div><div class="cmblocks-counter__counter" style="color:#ffffff;font-size:3.27rem;justify-content:center"><?php esc_html_e('0', 'cm-blocks'); ?></div><div class="cmblocks-counter__suffix" style="color:#ffffff;padding-left:0px;font-size:3.27rem"><?php esc_html_e('k', 'cm-blocks'); ?></div></div><div class="cmblocks-counter__title" style="color:#ffffff;font-size:1.05rem;text-align:center"><?php esc_html_e('Satisfied Customers', 'cm-blocks'); ?></div></div></div>
					<!-- /wp:cmblocks/counter --></div>
				<!-- /wp:column -->

				<!-- wp:column {"style":{"color":{"background":"#cccccc57"}}} -->
				<div class="wp-block-column has-background" style="background-color:#cccccc57"><!-- wp:cmblocks/counter {"title":"Cases Completed","endValue":"16","duration":"500","suffix":"k","titleColor":"#ffffff","counterColor":"#ffffff","suffixColor":"#ffffff","counterFontSize":"3.27rem","titleFontSize":"1.05rem","counterAlignment":"center","titleAlignment":"center","startFromScratch":true,"style":{"typography":{"textTransform":"none","fontStyle":"normal","fontWeight":"600"},"spacing":{"padding":{"top":"var:preset|spacing|40","bottom":"var:preset|spacing|40","left":"0","right":"0"}}}} -->
					<div class="wp-block-cmblocks-counter cmblocks-counter" style="padding-top:var(--wp--preset--spacing--40);padding-right:0;padding-bottom:var(--wp--preset--spacing--40);padding-left:0;font-style:normal;font-weight:600;text-transform:none;background:" role="timer" aria-live="polite" aria-label="<?php esc_html_e('Counter', 'cm-blocks'); ?>"><div class="cmblocks-counter__wrapper" style="background:" data-end-value="16" data-start-value="0" data-duration="500" data-separator=""><div class="cmblocks-counter__main" style="justify-content:center"><div class="cmblocks-counter__prefix" style="color:;padding-right:0;font-size:3.27rem"></div><div class="cmblocks-counter__counter" style="color:#ffffff;font-size:3.27rem;justify-content:center"><?php esc_html_e('0', 'cm-blocks'); ?></div><div class="cmblocks-counter__suffix" style="color:#ffffff;padding-left:0px;font-size:3.27rem"><?php esc_html_e('k', 'cm-blocks'); ?></div></div><div class="cmblocks-counter__title" style="color:#ffffff;font-size:1.05rem;text-align:center"><?php esc_html_e('Cases Completed', 'cm-blocks'); ?></div></div></div>
					<!-- /wp:cmblocks/counter --></div>
				<!-- /wp:column --></div>
			<!-- /wp:columns -->

			<!-- wp:columns -->
			<div class="wp-block-columns"><!-- wp:column {"style":{"color":{"background":"#cccccc57"}}} -->
				<div class="wp-block-column has-background" style="background-color:#cccccc57"><!-- wp:cmblocks/counter {"title":"Years of Experience","endValue":"15","duration":"500","titleColor":"#ffffff","counterColor":"#ffffff","suffixColor":"#ffffff","counterFontSize":"3.27rem","titleFontSize":"1.05rem","counterAlignment":"center","titleAlignment":"center","startFromScratch":true,"style":{"typography":{"textTransform":"none","fontStyle":"normal","fontWeight":"600"},"spacing":{"padding":{"top":"var:preset|spacing|40","bottom":"var:preset|spacing|40","left":"0","right":"0"}}}} -->
					<div class="wp-block-cmblocks-counter cmblocks-counter" style="padding-top:var(--wp--preset--spacing--40);padding-right:0;padding-bottom:var(--wp--preset--spacing--40);padding-left:0;font-style:normal;font-weight:600;text-transform:none;background:" role="timer" aria-live="polite" aria-label="<?php esc_html_e('Counter', 'cm-blocks'); ?>"><div class="cmblocks-counter__wrapper" style="background:" data-end-value="15" data-start-value="0" data-duration="500" data-separator=""><div class="cmblocks-counter__main" style="justify-content:center"><div class="cmblocks-counter__prefix" style="color:;padding-right:0;font-size:3.27rem"></div><div class="cmblocks-counter__counter" style="color:#ffffff;font-size:3.27rem;justify-content:center"><?php esc_html_e('0', 'cm-blocks'); ?></div><div class="cmblocks-counter__suffix" style="color:#ffffff;padding-left:0;font-size:3.27rem"></div></div><div class="cmblocks-counter__title" style="color:#ffffff;font-size:1.05rem;text-align:center"><?php esc_html_e('Years of Experience', 'cm-blocks'); ?></div></div></div>
					<!-- /wp:cmblocks/counter --></div>
				<!-- /wp:column -->

				<!-- wp:column {"style":{"color":{"background":"#cccccc57"}}} -->
				<div class="wp-block-column has-background" style="background-color:#cccccc57"><!-- wp:cmblocks/counter {"title":"Our Awards","endValue":"10","duration":"500","titleColor":"#ffffff","counterColor":"#ffffff","suffixColor":"#ffffff","counterFontSize":"3.27rem","titleFontSize":"1.05rem","counterAlignment":"center","titleAlignment":"center","startFromScratch":true,"style":{"typography":{"textTransform":"none","fontStyle":"normal","fontWeight":"600"},"spacing":{"padding":{"top":"var:preset|spacing|40","bottom":"var:preset|spacing|40","left":"0","right":"0"}}}} -->
					<div class="wp-block-cmblocks-counter cmblocks-counter" style="padding-top:var(--wp--preset--spacing--40);padding-right:0;padding-bottom:var(--wp--preset--spacing--40);padding-left:0;font-style:normal;font-weight:600;text-transform:none;background:" role="timer" aria-live="polite" aria-label="<?php esc_html_e('Counter', 'cm-blocks'); ?>"><div class="cmblocks-counter__wrapper" style="background:" data-end-value="10" data-start-value="0" data-duration="500" data-separator=""><div class="cmblocks-counter__main" style="justify-content:center"><div class="cmblocks-counter__prefix" style="color:;padding-right:0;font-size:3.27rem"></div><div class="cmblocks-counter__counter" style="color:#ffffff;font-size:3.27rem;justify-content:center"><?php esc_html_e('0', 'cm-blocks'); ?></div><div class="cmblocks-counter__suffix" style="color:#ffffff;padding-left:0;font-size:3.27rem"></div></div><div class="cmblocks-counter__title" style="color:#ffffff;font-size:1.05rem;text-align:center"><?php esc_html_e('Our Awards', 'cm-blocks'); ?></div></div></div>
					<!-- /wp:cmblocks/counter --></div>
				<!-- /wp:column --></div>
			<!-- /wp:columns --></div></div>
	<!-- /wp:cover --></div>
<!-- /wp:group -->
