<?php
/**
 * Title: Counter Plain Horizontal
 * Slug: counter-plain-horizontal
 * Categories: codemanas
 * Keywords: codemanas
 * Block Types: codemanas/cmblocks--counter
 */
if (!defined('ABSPATH')) {
	exit; // Exit if accessed directly
}
?>
<!-- wp:cover {"dimRatio":0,"overlayColor":"background","contentPosition":"center center","isDark":false,"align":"wide"} -->
<div class="wp-block-cover alignwide is-light"><span aria-hidden="true" class="wp-block-cover__background has-background-background-color has-background-dim-0 has-background-dim"></span><div class="wp-block-cover__inner-container"><!-- wp:columns {"style":{"spacing":{"blockGap":{"top":"0","left":"var:preset|spacing|40"}}}} -->
		<div class="wp-block-columns"><!-- wp:column -->
			<div class="wp-block-column"><!-- wp:cmblocks/counter {"title":"\u003cem\u003eVisitors\u003c/em\u003e","endValue":"25","suffix":"M+","counterFontSize":"3.27rem","titleFontSize":"1.05rem","counterAlignment":"center","titleAlignment":"center","startFromScratch":true,"style":{"spacing":{"padding":{"top":"var:preset|spacing|30","bottom":"var:preset|spacing|30","left":"2rem","right":"2rem"}},"border":{"width":"2px","color":"#000000","radius":"15px"},"typography":{"fontStyle":"normal","fontWeight":"500"}},"className":"has-x-large-font-size"} -->
				<div class="wp-block-cmblocks-counter cmblocks-counter has-x-large-font-size has-border-color" style="border-color:#000000;border-width:2px;border-radius:15px;padding-top:var(--wp--preset--spacing--30);padding-right:2rem;padding-bottom:var(--wp--preset--spacing--30);padding-left:2rem;font-style:normal;font-weight:500;background:" role="timer" aria-live="polite" aria-label="<?php esc_html_e('Counter', 'cm-blocks'); ?>"><div class="cmblocks-counter__wrapper" style="background:" data-end-value="25" data-start-value="0" data-duration="1200" data-separator=""><div class="cmblocks-counter__main" style="justify-content:center"><div class="cmblocks-counter__prefix" style="color:;padding-right:0;font-size:3.27rem"></div><div class="cmblocks-counter__counter" style="color:;font-size:3.27rem;justify-content:center"><?php esc_html_e('0', 'cm-blocks'); ?></div><div class="cmblocks-counter__suffix" style="color:;padding-left:0px;font-size:3.27rem"><?php esc_html_e('M+', 'cm-blocks'); ?></div></div><div class="cmblocks-counter__title" style="color:;font-size:1.05rem;text-align:center"><em><?php esc_html_e('Visitors', 'cm-blocks'); ?></em></div></div></div>
				<!-- /wp:cmblocks/counter --></div>
			<!-- /wp:column -->

			<!-- wp:column -->
			<div class="wp-block-column"><!-- wp:cmblocks/counter {"title":"\u003cem\u003eCase Studies\u003c/em\u003e","endValue":"575","suffix":"+","counterFontSize":"3.27rem","titleFontSize":"1.05rem","counterAlignment":"center","titleAlignment":"center","startFromScratch":true,"style":{"spacing":{"padding":{"top":"var:preset|spacing|30","bottom":"var:preset|spacing|30","left":"2rem","right":"2rem"}},"border":{"width":"2px","color":"#000000","radius":"15px"},"typography":{"fontStyle":"normal","fontWeight":"500"}},"className":"has-x-large-font-size"} -->
				<div class="wp-block-cmblocks-counter cmblocks-counter has-x-large-font-size has-border-color" style="border-color:#000000;border-width:2px;border-radius:15px;padding-top:var(--wp--preset--spacing--30);padding-right:2rem;padding-bottom:var(--wp--preset--spacing--30);padding-left:2rem;font-style:normal;font-weight:500;background:" role="timer" aria-live="polite" aria-label="<?php esc_html_e('Counter', 'cm-blocks'); ?>"><div class="cmblocks-counter__wrapper" style="background:" data-end-value="575" data-start-value="0" data-duration="1200" data-separator=""><div class="cmblocks-counter__main" style="justify-content:center"><div class="cmblocks-counter__prefix" style="color:;padding-right:0;font-size:3.27rem"></div><div class="cmblocks-counter__counter" style="color:;font-size:3.27rem;justify-content:center"><?php esc_html_e('0', 'cm-blocks'); ?></div><div class="cmblocks-counter__suffix" style="color:;padding-left:0px;font-size:3.27rem"><?php esc_html_e('+', 'cm-blocks'); ?></div></div><div class="cmblocks-counter__title" style="color:;font-size:1.05rem;text-align:center"><em><?php esc_html_e('Case Studies', 'cm-blocks'); ?></em></div></div></div>
				<!-- /wp:cmblocks/counter --></div>
			<!-- /wp:column -->

			<!-- wp:column -->
			<div class="wp-block-column"><!-- wp:cmblocks/counter {"title":"\u003cem\u003eTransactions\u003c/em\u003e","endValue":"30","suffix":"M","counterFontSize":"3.27rem","titleFontSize":"1.05rem","counterAlignment":"center","titleAlignment":"center","startFromScratch":true,"style":{"spacing":{"padding":{"top":"var:preset|spacing|30","bottom":"var:preset|spacing|30","left":"2rem","right":"2rem"}},"border":{"width":"2px","color":"#000000","radius":"15px"},"typography":{"fontStyle":"normal","fontWeight":"500"}},"className":"has-x-large-font-size"} -->
				<div class="wp-block-cmblocks-counter cmblocks-counter has-x-large-font-size has-border-color" style="border-color:#000000;border-width:2px;border-radius:15px;padding-top:var(--wp--preset--spacing--30);padding-right:2rem;padding-bottom:var(--wp--preset--spacing--30);padding-left:2rem;font-style:normal;font-weight:500;background:" role="timer" aria-live="polite" aria-label="<?php esc_html_e('Counter', 'cm-blocks'); ?>"><div class="cmblocks-counter__wrapper" style="background:" data-end-value="30" data-start-value="0" data-duration="1200" data-separator=""><div class="cmblocks-counter__main" style="justify-content:center"><div class="cmblocks-counter__prefix" style="color:;padding-right:0;font-size:3.27rem"></div><div class="cmblocks-counter__counter" style="color:;font-size:3.27rem;justify-content:center"><?php esc_html_e('0', 'cm-blocks'); ?></div><div class="cmblocks-counter__suffix" style="color:;padding-left:0px;font-size:3.27rem"><?php esc_html_e('M', 'cm-blocks'); ?></div></div><div class="cmblocks-counter__title" style="color:;font-size:1.05rem;text-align:center"><em><?php esc_html_e('Transactions', 'cm-blocks'); ?></em></div></div></div>
				<!-- /wp:cmblocks/counter --></div>
			<!-- /wp:column -->

			<!-- wp:column -->
			<div class="wp-block-column"><!-- wp:cmblocks/counter {"title":"\u003cem\u003eLeads\u003c/em\u003e","endValue":"5","suffix":"M","counterFontSize":"3.27rem","titleFontSize":"1.05rem","counterAlignment":"center","titleAlignment":"center","startFromScratch":true,"style":{"spacing":{"padding":{"top":"var:preset|spacing|30","bottom":"var:preset|spacing|30","left":"2rem","right":"2rem"}},"border":{"width":"2px","color":"#000000","radius":"15px"},"typography":{"fontStyle":"normal","fontWeight":"500"}},"className":"has-x-large-font-size"} -->
				<div class="wp-block-cmblocks-counter cmblocks-counter has-x-large-font-size has-border-color" style="border-color:#000000;border-width:2px;border-radius:15px;padding-top:var(--wp--preset--spacing--30);padding-right:2rem;padding-bottom:var(--wp--preset--spacing--30);padding-left:2rem;font-style:normal;font-weight:500;background:" role="timer" aria-live="polite" aria-label="<?php esc_html_e('Counter', 'cm-blocks'); ?>"><div class="cmblocks-counter__wrapper" style="background:" data-end-value="5" data-start-value="0" data-duration="1200" data-separator=""><div class="cmblocks-counter__main" style="justify-content:center"><div class="cmblocks-counter__prefix" style="color:;padding-right:0;font-size:3.27rem"></div><div class="cmblocks-counter__counter" style="color:;font-size:3.27rem;justify-content:center"><?php esc_html_e('0', 'cm-blocks'); ?></div><div class="cmblocks-counter__suffix" style="color:;padding-left:0px;font-size:3.27rem"><?php esc_html_e('M', 'cm-blocks'); ?></div></div><div class="cmblocks-counter__title" style="color:;font-size:1.05rem;text-align:center"><em><?php esc_html_e('Leads', 'cm-blocks'); ?></em></div></div></div>
				<!-- /wp:cmblocks/counter --></div>
			<!-- /wp:column --></div>
		<!-- /wp:columns --></div></div>
<!-- /wp:cover -->
