<?php
/**
 * Title: Vertical Progress Bar
 * Slug: progress-bar-vertical
 * Categories: codemanas
 * Keywords: codemanas
 * Block Types: codemanas/cmblocks--progress-bar
 */
if (!defined('ABSPATH')) {
	exit; // Exit if accessed directly
}
?>

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:heading {"textAlign":"center","style":{"typography":{"fontStyle":"normal","fontWeight":"600"}},"fontFamily":"body"} -->
	<h2 class="wp-block-heading has-text-align-center has-body-font-family" style="font-style:normal;font-weight:600"><?php esc_html_e('Task Report', 'cm-blocks'); ?></h2>
	<!-- /wp:heading -->

	<!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|50","margin":{"top":"var:preset|spacing|40"}}},"layout":{"type":"flex","flexWrap":"nowrap","justifyContent":"center"}} -->
	<div class="wp-block-group" style="margin-top:var(--wp--preset--spacing--40)"><!-- wp:cmblocks/progress-bar {"title":"Task 1","percentage":68,"height":34.81,"borderRadius":4,"titleColor":"#636363","indicatorBackground":"#6a9737","titlePosition":"outside-top","percentagePosition":"append","layout":"vertical","startFromScratch":true} -->
		<div class="wp-block-cmblocks-progress-bar cmblocks-progress-bar" style="padding-top:0;height:calc(500px)"><div class="cmblocks-progress-bar cmblocks-progress-bar-vertical"><div class="cmblocks-progress-bar__wrapper" style="height:34.81px;width:500px;border-radius:4px;background:#E7E7E7"><div id="cmProgressBar" class="cmblocks-progress-bar__title" style="display:block;font-size:calc( 34.81 * 0.55px );color:#636363;top:-34.81px"><?php esc_html_e('Task 1', 'cm-blocks'); ?></div><div role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="68" aria-labelledby="cmProgressBar" class="cmblocks-progress-bar__indicator" style="height:34.81px;border-radius:4px 0 0  4px;background:#6a9737" data-percentage="68" data-duration="500" data-border-radius="4"><div class="cmblocks-progress-bar__percentage--append" style="display:block;font-size:calc( 34.81 * 0.55px );color:#2D2D2D;right:calc(-34.81px - 20px)"><?php esc_html_e('68%', 'cm-blocks'); ?></div></div><div class="cmblocks-progress-bar__percentage" style="display:none;font-size:calc( 34.81 * 0.55px );color:#2D2D2D;top:5%"><?php esc_html_e('68%', 'cm-blocks'); ?></div></div></div></div>
		<!-- /wp:cmblocks/progress-bar -->

		<!-- wp:cmblocks/progress-bar {"title":"Task 2","percentage":59,"height":34.81,"borderRadius":4,"titleColor":"#636363","indicatorBackground":"#636363","titlePosition":"outside-top","percentagePosition":"append","layout":"vertical","startFromScratch":true} -->
		<div class="wp-block-cmblocks-progress-bar cmblocks-progress-bar" style="padding-top:0;height:calc(500px)"><div class="cmblocks-progress-bar cmblocks-progress-bar-vertical"><div class="cmblocks-progress-bar__wrapper" style="height:34.81px;width:500px;border-radius:4px;background:#E7E7E7"><div id="cmProgressBar" class="cmblocks-progress-bar__title" style="display:block;font-size:calc( 34.81 * 0.55px );color:#636363;top:-34.81px"><?php esc_html_e('Task 2', 'cm-blocks'); ?></div><div role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="59" aria-labelledby="cmProgressBar" class="cmblocks-progress-bar__indicator" style="height:34.81px;border-radius:4px 0 0  4px;background:#636363" data-percentage="59" data-duration="500" data-border-radius="4"><div class="cmblocks-progress-bar__percentage--append" style="display:block;font-size:calc( 34.81 * 0.55px );color:#2D2D2D;right:calc(-34.81px - 20px)"><?php esc_html_e('59%', 'cm-blocks'); ?></div></div><div class="cmblocks-progress-bar__percentage" style="display:none;font-size:calc( 34.81 * 0.55px );color:#2D2D2D;top:5%"><?php esc_html_e('59%', 'cm-blocks'); ?></div></div></div></div>
		<!-- /wp:cmblocks/progress-bar -->

		<!-- wp:cmblocks/progress-bar {"title":"Task 3","percentage":40,"height":34.81,"borderRadius":4,"titleColor":"#636363","indicatorBackground":"#9b4848","titlePosition":"outside-top","percentagePosition":"append","layout":"vertical","startFromScratch":true} -->
		<div class="wp-block-cmblocks-progress-bar cmblocks-progress-bar" style="padding-top:0;height:calc(500px)"><div class="cmblocks-progress-bar cmblocks-progress-bar-vertical"><div class="cmblocks-progress-bar__wrapper" style="height:34.81px;width:500px;border-radius:4px;background:#E7E7E7"><div id="cmProgressBar" class="cmblocks-progress-bar__title" style="display:block;font-size:calc( 34.81 * 0.55px );color:#636363;top:-34.81px"><?php esc_html_e('Task 3', 'cm-blocks'); ?></div><div role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="40" aria-labelledby="cmProgressBar" class="cmblocks-progress-bar__indicator" style="height:34.81px;border-radius:4px 0 0  4px;background:#9b4848" data-percentage="40" data-duration="500" data-border-radius="4"><div class="cmblocks-progress-bar__percentage--append" style="display:block;font-size:calc( 34.81 * 0.55px );color:#2D2D2D;right:calc(-34.81px - 20px)"><?php esc_html_e('40%', 'cm-blocks'); ?></div></div><div class="cmblocks-progress-bar__percentage" style="display:none;font-size:calc( 34.81 * 0.55px );color:#2D2D2D;top:5%"><?php esc_html_e('40%', 'cm-blocks'); ?></div></div></div></div>
		<!-- /wp:cmblocks/progress-bar -->

		<!-- wp:cmblocks/progress-bar {"title":"Task 4","percentage":69,"height":34.81,"borderRadius":4,"titleColor":"#636363","indicatorBackground":"#613c99","titlePosition":"outside-top","percentagePosition":"append","layout":"vertical","startFromScratch":true} -->
		<div class="wp-block-cmblocks-progress-bar cmblocks-progress-bar" style="padding-top:0;height:calc(500px)"><div class="cmblocks-progress-bar cmblocks-progress-bar-vertical"><div class="cmblocks-progress-bar__wrapper" style="height:34.81px;width:500px;border-radius:4px;background:#E7E7E7"><div id="cmProgressBar" class="cmblocks-progress-bar__title" style="display:block;font-size:calc( 34.81 * 0.55px );color:#636363;top:-34.81px"><?php esc_html_e('Task 4', 'cm-blocks'); ?></div><div role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="69" aria-labelledby="cmProgressBar" class="cmblocks-progress-bar__indicator" style="height:34.81px;border-radius:4px 0 0  4px;background:#613c99" data-percentage="69" data-duration="500" data-border-radius="4"><div class="cmblocks-progress-bar__percentage--append" style="display:block;font-size:calc( 34.81 * 0.55px );color:#2D2D2D;right:calc(-34.81px - 20px)"><?php esc_html_e('69%', 'cm-blocks'); ?></div></div><div class="cmblocks-progress-bar__percentage" style="display:none;font-size:calc( 34.81 * 0.55px );color:#2D2D2D;top:5%"><?php esc_html_e('69%', 'cm-blocks'); ?></div></div></div></div>
		<!-- /wp:cmblocks/progress-bar -->

		<!-- wp:cmblocks/progress-bar {"title":"Task 5","percentage":84,"height":34.81,"borderRadius":4,"titleColor":"#636363","indicatorBackground":"#7d3466","titlePosition":"outside-top","percentagePosition":"append","layout":"vertical","startFromScratch":true} -->
		<div class="wp-block-cmblocks-progress-bar cmblocks-progress-bar" style="padding-top:0;height:calc(500px)"><div class="cmblocks-progress-bar cmblocks-progress-bar-vertical"><div class="cmblocks-progress-bar__wrapper" style="height:34.81px;width:500px;border-radius:4px;background:#E7E7E7"><div id="cmProgressBar" class="cmblocks-progress-bar__title" style="display:block;font-size:calc( 34.81 * 0.55px );color:#636363;top:-34.81px"><?php esc_html_e('Task 5', 'cm-blocks'); ?></div><div role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="84" aria-labelledby="cmProgressBar" class="cmblocks-progress-bar__indicator" style="height:34.81px;border-radius:4px 0 0  4px;background:#7d3466" data-percentage="84" data-duration="500" data-border-radius="4"><div class="cmblocks-progress-bar__percentage--append" style="display:block;font-size:calc( 34.81 * 0.55px );color:#2D2D2D;right:calc(-34.81px - 20px)"><?php esc_html_e('84%', 'cm-blocks'); ?></div></div><div class="cmblocks-progress-bar__percentage" style="display:none;font-size:calc( 34.81 * 0.55px );color:#2D2D2D;top:5%"><?php esc_html_e('84%', 'cm-blocks'); ?></div></div></div></div>
		<!-- /wp:cmblocks/progress-bar --></div>
	<!-- /wp:group --></div>
<!-- /wp:group -->
