<?php
/**
 * Title: Countdown With Gradient Background
 * Slug: countdown-with-gradient-background
 * Categories: codemanas
 * Keywords: codemanas
 * Block Types: codemanas/cmblocks--countdown
 */
if (!defined('ABSPATH')) {
	exit; // Exit if accessed directly
}
?>

<!-- wp:group {"style":{"color":{"gradient":"linear-gradient(135deg,rgb(34,169,203) 0%,rgb(0,181,169) 100%)"},"spacing":{"padding":{"top":"0","bottom":"0","left":"var:preset|spacing|20","right":"var:preset|spacing|20"}},"border":{"radius":"8px"}},"layout":{"type":"default"}} -->
<div class="wp-block-group has-background" style="border-radius:8px;background:linear-gradient(135deg,rgb(34,169,203) 0%,rgb(0,181,169) 100%);padding-top:0;padding-right:var(--wp--preset--spacing--20);padding-bottom:0;padding-left:var(--wp--preset--spacing--20)"><!-- wp:group {"align":"wide","style":{"spacing":{"margin":{"top":"0","bottom":"0"},"padding":{"right":"0","left":"0"}}},"layout":{"type":"flex","flexWrap":"nowrap","justifyContent":"center"}} -->
    <div class="wp-block-group alignwide" style="margin-top:0;margin-bottom:0;padding-right:0;padding-left:0"><!-- wp:cmblocks/countdown {"countdownDayText":" DAYS","countdownHourText":" HOURS","countdownMinuteText":" MINUTES","countdownSecondText":" SECONDS","countdownTextColor":"#ffffff","countdownDigitColor":"#ffffff","countdownSeparatorColor":"#ffffff","countdownBlockMargin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"countdownBlockBorder":{"style":"none","width":"0px","color":"#000"},"countdownBlockBorderRadius":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"countdownBlockPadding":{"top":"24px","right":"16px","bottom":"24px","left":"16px"},"countdownContentLayout":"column","countdownTextFontSize":"16px","countdownDigitFontSize":"58px","countdownSeparatorFontSize":"60px","countdownDateTime":"Fri, 24 Oct 2025 14:00:00 GMT","countdownDisplayDateTime":"2025-10-24T14:00:00","startFromScratch":true,"separatorMargin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"align":"wide","style":{"typography":{"fontStyle":"normal","fontWeight":"700"}}} -->
        <div style="font-style:normal;font-weight:700;--cmblocks-countdown__ticker-digit-color:#ffffff;--cmblocks-countdown__ticker-text-color:#ffffff;--cmblocks-countdown__ticker-text-font-size:16px;--cmblocks-countdown__ticker-digit-font-size:58px;--cmblocks-countdown__ticker-padding-top:24px;--cmblocks-countdown__ticker-padding-bottom:24px;--cmblocks-countdown__ticker-padding-left:16px;--cmblocks-countdown__ticker-padding-right:16px;--cmblocks-countdown__ticker-margin-top:0px;--cmblocks-countdown__ticker-margin-bottom:0px;--cmblocks-countdown__ticker-margin-left:0px;--cmblocks-countdown__ticker-margin-right:0px;--cmblocks-countdown__ticker-separator-font-size:60px;--cmblocks-countdown__ticker-separator-color:#ffffff;--cmblocks-countdown__separator-margin-top:0px;--cmblocks-countdown__separator-margin-bottom:0px;--cmblocks-countdown__separator-margin-left:0px;--cmblocks-countdown__separator-margin-right:0px;--cmblocks-countdown__ticker-border-top:0px none #000;--cmblocks-countdown__ticker-border-bottom:0px none #000;--cmblocks-countdown__ticker-border-left:0px none #000;--cmblocks-countdown__ticker-border-right:0px none #000;--cmblocks-countdown__ticker-border-radius:0px 0px 0px 0px" class="wp-block-cmblocks-countdown alignwide cmblocks-countdown" role="timer" aria-live="polite" aria-atomic="true" aria-label="<?php esc_html_e('Countdown Timer','cm-blocks'); ?>"><div data-countdown-datetime="Fri, 24 Oct 2025 14:00:00 GMT" class="cmblocks-countdown__ticker cmblocks-countdown__ticker--horizontal cmblocks-countdown__ticker--content-column" role="presentation"><span class="cmblocks-countdown__ticker-item cmblocks-countdown__ticker-days" aria-label="<?php esc_html_e('Days','cm-blocks'); ?>"><span class="cmblocks-countdown__ticker-digit"></span><span class="cmblocks-countdown__ticker-text"> DAYS</span></span><span class="cmblocks-countdown__ticker-separator">:</span><span class="cmblocks-countdown__ticker-item cmblocks-countdown__ticker-hours" aria-label="<?php esc_html_e('Hours','cm-blocks'); ?>"><span class="cmblocks-countdown__ticker-digit"></span><span class="cmblocks-countdown__ticker-text"> <?php esc_html_e('HOURS','cm-blocks'); ?></span></span><span class="cmblocks-countdown__ticker-separator">:</span><span class="cmblocks-countdown__ticker-item cmblocks-countdown__ticker-minutes" aria-label="<?php esc_html_e('Minutes','cm-blocks'); ?>"><span class="cmblocks-countdown__ticker-digit"></span><span class="cmblocks-countdown__ticker-text"> <?php esc_html_e('MINUTES','cm-blocks'); ?></span></span><span class="cmblocks-countdown__ticker-separator">:</span><span class="cmblocks-countdown__ticker-item cmblocks-countdown__ticker-seconds" aria-label="<?php esc_html_e('Seconds','cm-blocks'); ?>"><span class="cmblocks-countdown__ticker-digit"></span><span class="cmblocks-countdown__ticker-text"> <?php esc_html_e('SECONDS','cm-blocks'); ?></span></span></div></div>
        <!-- /wp:cmblocks/countdown --></div>
    <!-- /wp:group --></div>
<!-- /wp:group -->